# Generated by Django 4.2.2 on 2023-06-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title_photo',
            field=models.ImageField(default='no_photo', upload_to='uploads/title_photos/'),
            preserve_default=False,
        ),
    ]
