# Generated by Django 4.2.2 on 2023-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='', upload_to='covers', verbose_name='Book cover'),
            preserve_default=False,
        ),
    ]
