# Generated by Django 4.2.2 on 2023-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_book_title_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title_photo',
            field=models.ImageField(upload_to='media/title_photos/'),
        ),
    ]
