# Generated by Django 4.2.2 on 2023-06-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_book_photo'),
        ('Main', '0003_alter_book_title_photo'),
    ]

    operations = [
    ]
