# Generated by Django 4.2.2 on 2023-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_book_title_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default='not available yet', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title_photo',
            field=models.ImageField(upload_to='title_photos/'),
        ),
    ]
