# Generated by Django 4.2.2 on 2023-07-01 12:57

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_merge_0002_book_photo_0003_alter_book_title_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.AlterField(
            model_name='book',
            name='title_photo',
            field=models.ImageField(upload_to=Main.models.book_upload_location),
        ),
    ]
