# Generated by Django 4.2.2 on 2023-07-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_book_book_alter_book_title_photo'),
        ('Main', '0005_remove_book_photo_alter_book_title_photo'),
    ]

    operations = [
    ]
