# Generated by Django 4.2.2 on 2023-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_merge_20230701_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_release',
            field=models.IntegerField(null=True),
        ),
    ]
